GET http://localhost:3000/user-api
###
POST http://localhost:3000/user-api/user 
Content-Type: application/json

{   "firstName":"dfwe", 
    "email": "user1mail.com",
    "password":"12234",
    "isActive": true
}
###
POST http://localhost:3000/user-api/user-contribute
Content-Type: application/json

{
  "question": "What is the use of useEffect in React?",
  "tag": "React",
  
  "company": "Meta",
  "role": "Frontend Developer",
  "solution": "useEffect is used to perform side effects like data fetching, subscriptions, etc."
}
###
POST http://localhost:3000/user-api/user-contribute
Content-Type: application/json

{
  "question": "What is the use of functions in C lang?",
  "tag": "C lang",
  "company": "Meta",
  "role": "Software Developer",
  "solution": "useEffect is used to perform side effects like data fetching, subscriptions, etc."
}
###
post http://localhost:3000/user-api/contact
Content-Type: application/json

{
  "firstName":"kanth",
  "lastName":"TS",
  "email":"tsidda@gmail.com",
  "message":"kbwhvdbk"
}

###
post http://localhost:3000/email-api/email
Content-Type: application/json

{  "from":"usagemail123@gmail.com",
  "to":"tsiddakanth@gmail.com",
  "subject":"kjnksd",
  "message":"jnrd"
}